spring:
  jpa:
    hibernate:
      ddl-auto: update
    
  datasource:
    username: root
    password: myMySqlId420*
    url: jdbc:mysql://localhost:3306/cultural_fest_student_management
  
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
server:
  port: 8081
  servlet:
    context-path: /studentcollegefest
